### PR TITLE
Ee toplevel pslib

### PR DESCRIPTION
**Pull request by jphaneuf**
Add DC converters to lib
Custom parts, need review
https://www.digikey.com/product-detail/en/recom-power/R-745.0P/945-1028-ND/2256208
https://www.digikey.com/products/en?keywords=V36SE12004

### CODE REVIEW

**Comment by davidjevans** [comment]
Add >Name to silkscreen, other than that it looks good! ;)

**Comment by jphaneuf** [comment]
@davidjevans added!

**Comment by davidjevans** [comment]
I see pin names added to the silkscreen of the dc-dc converters, did you also put on name silkscreen for entire component?  If so, I don't see it.

**Comment by jphaneuf** [comment]
@davidjevans added sch >Name >Value

**Pull request merged**
